# Generated by Django 5.2.5 on 2025-12-05 04:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Дата отчёта', verbose_name='Дата')),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма от продаж + погашенных долгов', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Доход')),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Показатель неуплаченных товаров', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Непогашенный долг')),
                ('paid_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Не в диаграмме, только в поле', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Погашенные долги')),
                ('bonus_count', models.IntegerField(default=0, help_text='Считаются по количеству, не влияют на сумму', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бонусы (штук)')),
                ('defect_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма убытка, идёт в минус', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Брак')),
                ('expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ручной ввод от партнёров', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Расходы')),
                ('orders_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество заказов')),
                ('products_sold_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество проданных товаров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='stores.city', verbose_name='Город')),
                ('partner', models.ForeignKey(blank=True, help_text='Null = общая статистика', limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='stores.region', verbose_name='Область')),
                ('store', models.ForeignKey(blank=True, help_text='Null = общая статистика', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Ежедневный отчёт',
                'verbose_name_plural': 'Ежедневные отчёты',
                'db_table': 'daily_reports',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='daily_repor_date_667f09_idx'), models.Index(fields=['store', 'date'], name='daily_repor_store_i_166035_idx'), models.Index(fields=['partner', 'date'], name='daily_repor_partner_5204e3_idx'), models.Index(fields=['region', 'date'], name='daily_repor_region__2fe136_idx'), models.Index(fields=['city', 'date'], name='daily_repor_city_id_26c2d7_idx')],
                'unique_together': {('date', 'store', 'partner', 'region', 'city')},
            },
        ),
    ]
