# Generated by Django 6.0.2 on 2026-03-31 17:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Финансовая стоимость выданных бонусов (количество × цена)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость бонусов'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bonus_count',
            field=models.IntegerField(default=0, help_text='Считаются по количеству', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бонусы (штук)'),
        ),
    ]
