# Generated by Django 6.0.2 on 2026-04-01 20:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_bonus_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='sold_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Общая сумма проданных товаров (без бонусов)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма продаж'),
        ),
    ]
