# Generated by Django 5.2.5 on 2025-12-05 04:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название области')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='stores.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Используется для поиска', max_length=200, verbose_name='Название магазина')),
                ('inn', models.CharField(db_index=True, help_text='Уникальный идентификатор магазина (12-14 цифр)', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать от 12 до 14 цифр', regex='^\\d{12,14}$')], verbose_name='ИНН')),
                ('owner_name', models.CharField(db_index=True, help_text='Используется для поиска', max_length=200, verbose_name='ФИО владельца магазина')),
                ('phone', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Формат телефона: +996XXXXXXXXX (9 цифр после +996)', regex='^\\+996\\d{9}$')], verbose_name='Телефон магазина')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес магазина')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('debt', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), help_text='Может быть отрицательным (переплата)', max_digits=14, verbose_name='Текущий долг')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма всех погашений за всё время', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Всего погашено')),
                ('approval_status', models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', help_text='Магазин должен быть одобрен админом для работы', max_length=20, verbose_name='Статус одобрения')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Заблокированный магазин не может создавать/получать заказы', verbose_name='Активен (не заблокирован)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(help_text='Используется для фильтрации и поиска', on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.city', verbose_name='Город')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stores', to=settings.AUTH_USER_MODEL, verbose_name='Создал (пользователь)')),
                ('region', models.ForeignKey(help_text='Используется для фильтрации', on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.region', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Инвентарь магазина',
                'verbose_name_plural': 'Инвентарь магазинов',
                'db_table': 'store_inventory',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='StoreSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Активный магазин для пользователя. Только один может быть True.', verbose_name='Текущий выбор')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора')),
                ('deselected_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены выбора')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'store'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_selections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выбор магазина',
                'verbose_name_plural': 'Выборы магазинов',
                'db_table': 'store_selections',
                'ordering': ['-selected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region', 'name'], name='cities_region__8de1f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'name')},
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['inn'], name='stores_inn_866dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='stores_name_b54c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner_name'], name='stores_owner_n_4b54b6_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['phone'], name='stores_phone_b0dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['region', 'city'], name='stores_region__5dbfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['debt'], name='stores_debt_400952_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'approval_status'], name='stores_is_acti_195af4_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at'], name='stores_created_4eedc7_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['store', 'product'], name='store_inven_store_i_a52619_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['store', 'quantity'], name='store_inven_store_i_584231_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='storeselection',
            index=models.Index(fields=['user', 'is_current'], name='store_selec_user_id_a28247_idx'),
        ),
        migrations.AddIndex(
            model_name='storeselection',
            index=models.Index(fields=['store', 'is_current'], name='store_selec_store_i_d354b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeselection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_store_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='storeselection',
            unique_together={('user', 'store')},
        ),
    ]
