# Generated by Django 5.2.5 on 2025-11-28 08:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='stores.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ['region', 'name'],
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма возврата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина возврата')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ идемпотентности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Возврат товаров',
                'verbose_name_plural': 'Возвраты товаров',
                'db_table': 'return_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='products.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.returnrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Позиция возврата',
                'verbose_name_plural': 'Позиции возвратов',
                'db_table': 'return_request_items',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название магазина')),
                ('inn', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать от 12 до 14 цифр', regex='^\\d{12,14}$')], verbose_name='ИНН')),
                ('owner_name', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('phone', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Формат телефона: +996XXXXXXXXX', regex='^\\+996\\d{9}$')], verbose_name='Телефон')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Текущий долг')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Всего погашено')),
                ('approval_status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='pending', max_length=20, verbose_name='Статус одобрения')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='При деактивации партнёры не могут взаимодействовать с магазином', verbose_name='Активен (не заморожен)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.city', verbose_name='Город')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stores', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Инвентарь магазина',
                'verbose_name_plural': 'Инвентарь магазинов',
                'db_table': 'store_inventory',
            },
        ),
        migrations.CreateModel(
            name='StoreProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_requests', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Wishlist товар',
                'verbose_name_plural': 'Wishlist товары',
                'db_table': 'store_product_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('idempotency_key', models.CharField(blank=True, help_text='Защита от повторной отправки', max_length=100, null=True, unique=True, verbose_name='Ключ идемпотентности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Запрос магазина',
                'verbose_name_plural': 'Запросы магазинов',
                'db_table': 'store_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='products.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.storerequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Позиция запроса',
                'verbose_name_plural': 'Позиции запросов',
                'db_table': 'store_request_items',
            },
        ),
        migrations.CreateModel(
            name='StoreSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True, help_text='Активный магазин для пользователя', verbose_name='Текущий выбор')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'store'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_selections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выбор магазина',
                'verbose_name_plural': 'Выборы магазинов',
                'db_table': 'store_selections',
            },
        ),
        migrations.CreateModel(
            name='PartnerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_inventory', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Инвентарь партнёра',
                'verbose_name_plural': 'Инвентарь партнёров',
                'db_table': 'partner_inventory',
                'unique_together': {('partner', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['partner', 'created_at'], name='return_requ_partner_d35914_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='return_requ_status_736d08_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['inn'], name='stores_inn_866dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['phone'], name='stores_phone_b0dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['region', 'city'], name='stores_region__5dbfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['debt'], name='stores_debt_400952_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'approval_status'], name='stores_is_acti_195af4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('store', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='storeproductrequest',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='storerequest',
            index=models.Index(fields=['store', 'created_at'], name='store_reque_store_i_b6d370_idx'),
        ),
        migrations.AddIndex(
            model_name='storerequest',
            index=models.Index(fields=['idempotency_key'], name='store_reque_idempot_8435f4_idx'),
        ),
        migrations.AddIndex(
            model_name='storeselection',
            index=models.Index(fields=['user', 'is_current'], name='store_selec_user_id_a28247_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeselection',
            unique_together={('user', 'store')},
        ),
    ]
