# Generated by Django 5.2.5 on 2025-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='approved', help_text='Магазины автоматически одобряются при создании', max_length=20, verbose_name='Статус одобрения'),
        ),
    ]
