# Generated by Django 5.2.5 on 2026-01-13 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_set_store_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(default=1, help_text='v3.0: Пользователь, создавший магазин', limit_choices_to={'role': 'store'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name='Владелец магазина'),
            preserve_default=False,
        ),
    ]
