# Generated by Django 5.2.5 on 2026-01-29 04:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_make_owner_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='bonus_count',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Количество бесплатных товаров (каждый 21-й)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Бонусных товаров'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='defective_count',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Количество товаров, отмеченных как брак', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Бракованных товаров'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='paid_count',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Количество товаров, за которые магазин заплатил', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оплаченных товаров'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Только для весовых товаров', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Общий вес (кг)'),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общее количество'),
        ),
    ]
