# Generated by Django 5.2.5 on 2026-01-29 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_weight_to_defective'),
        ('stores', '0007_add_weight_fields_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinventory',
            name='last_partner_request',
            field=models.ForeignKey(blank=True, help_text='Запрос, через который товары попали в инвентарь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updates', to='orders.partnerrequest', verbose_name='Последний запрос'),
        ),
    ]
