# Generated by Django 5.2.5 on 2026-02-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_preview_to_productimage'),
        ('stores', '0009_cleanup_storeselection_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_inventory', to='products.product'),
        ),
    ]
