# Generated by Django 5.2.5 on 2026-02-15 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_partnerrequestitem_unique_together_and_more'),
        ('products', '0007_add_preview_to_productimage'),
        ('stores', '0010_product_cascade_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partnerinventory',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='Товар получен как бонус (бесплатно)', verbose_name='Бонусный товар'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerinventory',
            unique_together={('partner', 'product', 'is_bonus')},
        ),
        migrations.AddIndex(
            model_name='partnerinventory',
            index=models.Index(fields=['is_bonus'], name='partner_inv_is_bonu_392384_idx'),
        ),
    ]
