# Generated by Django 6.0.2 on 2026-02-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_partnerinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='approved', help_text='Магазины автоматически одобряются при создании', max_length=20, verbose_name='Статус     одобрения'),
        ),
    ]
