# Generated by Django 5.2.5 on 2025-12-05 04:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма заказа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.PROTECT, related_name='partner_orders', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Заказ партнёра',
                'verbose_name_plural': 'Заказы партнёров',
                'db_table': 'partner_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.partnerorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_order_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа партнёра',
                'verbose_name_plural': 'Позиции заказов партнёров',
                'db_table': 'partner_order_items',
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('in_transit', 'В пути'), ('accepted', 'Принят'), ('rejected', 'Отказано')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма заказа')),
                ('prepayment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Указывает партнёр при подтверждении', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Предоплата')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Автоматически: total_amount - prepayment_amount', max_digits=14, verbose_name='Сумма в долг')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оплачено')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('idempotency_key', models.CharField(blank=True, help_text='Защита от повторной отправки', max_length=64, null=True, unique=True, verbose_name='Idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил (партнёр)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('partner', models.ForeignKey(blank=True, help_text='Назначается при переходе в статус IN_TRANSIT', limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Проверил (админ)')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ магазина',
                'verbose_name_plural': 'Заказы магазинов',
                'db_table': 'store_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Уменьшит долг магазина', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма брака')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина брака')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects', to='products.product', verbose_name='Товар')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL, verbose_name='Кто сообщил')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defects', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defective_products', to='orders.storeorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Бракованный товар',
                'verbose_name_plural': 'Бракованные товары',
                'db_table': 'defective_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма погашения долга', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Кто оплатил')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял оплату')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='orders.storeorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Погашение долга',
                'verbose_name_plural': 'Погашения долгов',
                'db_table': 'debt_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('is_bonus', models.BooleanField(default=False, help_text='Бесплатный товар (каждый 21-й)', verbose_name='Бонусная позиция')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.storeorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_order_items', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа магазина',
                'verbose_name_plural': 'Позиции заказов магазинов',
                'db_table': 'store_order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('store', 'Заказ магазина'), ('partner', 'Заказ партнёра')], default='store_order', max_length=16, verbose_name='Тип объекта')),
                ('order_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('old_status', models.CharField(blank=True, max_length=16, verbose_name='Старый статус')),
                ('new_status', models.CharField(blank=True, default='', max_length=16, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to='products.product', verbose_name='Товар (опционально)')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
                'db_table': 'order_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_type', 'order_id'], name='order_histo_order_t_31ed9c_idx'), models.Index(fields=['-created_at'], name='order_histo_created_687ff6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['partner', '-created_at'], name='partner_ord_partner_3ab269_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['status'], name='partner_ord_status_868ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', '-created_at'], name='store_order_store_i_e0db5c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['partner', '-created_at'], name='store_order_partner_3affa6_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['status'], name='store_order_status_1814f8_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['reviewed_by'], name='store_order_reviewe_69e504_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['confirmed_by'], name='store_order_confirm_99c5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['-created_at'], name='store_order_created_886156_idx'),
        ),
        migrations.AddIndex(
            model_name='defectiveproduct',
            index=models.Index(fields=['order', '-created_at'], name='defective_p_order_i_b5b8db_idx'),
        ),
        migrations.AddIndex(
            model_name='defectiveproduct',
            index=models.Index(fields=['status'], name='defective_p_status_6017ea_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['order', '-created_at'], name='debt_paymen_order_i_ce598e_idx'),
        ),
    ]
