# Generated by Django 5.2.5 on 2025-11-28 08:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма возврата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Возврат по заказу',
                'verbose_name_plural': 'Возвраты по заказам',
                'db_table': 'order_returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина по позиции')),
            ],
            options={
                'verbose_name': 'Позиция возврата по заказу',
                'verbose_name_plural': 'Позиции возвратов по заказам',
                'db_table': 'order_return_items',
            },
        ),
        migrations.CreateModel(
            name='PartnerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма заказа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('idempotency_key', models.CharField(blank=True, help_text='Для защиты от повторной отправки заказа с фронта', max_length=64, null=True, unique=True, verbose_name='Idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Заказ партнёра',
                'verbose_name_plural': 'Заказы партнёров',
                'db_table': 'partner_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Позиция заказа партнёра',
                'verbose_name_plural': 'Позиции заказов партнёров',
                'db_table': 'partner_order_items',
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма заказа')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма в долг')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Idempotency key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Заказ магазина',
                'verbose_name_plural': 'Заказы магазинов',
                'db_table': 'store_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Бонусная позиция')),
            ],
            options={
                'verbose_name': 'Позиция заказа магазина',
                'verbose_name_plural': 'Позиции заказов магазинов',
                'db_table': 'store_order_items',
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments_made', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Погашение долга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('partner', 'Заказ партнёра'), ('store', 'Заказ магазина'), ('return', 'Возврат по заказу')], max_length=16, null=True, verbose_name='Тип объекта')),
                ('order_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('old_status', models.CharField(blank=True, max_length=16, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=16, null=True, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
                'db_table': 'order_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
