# Generated by Django 5.2.5 on 2025-12-29 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0005_expense_unit_type_product_manual_price_and_more'),
        ('stores', '0002_alter_store_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='partnerorderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=16, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_id',
            field=models.PositiveIntegerField(verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('store', 'Заказ магазина')], max_length=10, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил (партнёр)'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total_amount - prepayment_amount', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Долг'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Назначается админом или автоматически', limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Указывается партнёром при подтверждении', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел (админ)'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_transit', 'В пути'), ('accepted', 'Принят'), ('rejected', 'Отказано')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.DeleteModel(
            name='PartnerOrder',
        ),
        migrations.DeleteModel(
            name='PartnerOrderItem',
        ),
    ]
