# Generated by Django 5.2.5 on 2026-01-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_partner_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='order_type',
            field=models.CharField(choices=[('preorder', 'Предзаказ'), ('manual', 'Ручной сбор')], default='preorder', help_text='Предзаказ или ручной сбор партнёром', max_length=10, verbose_name='Тип заказа'),
        ),
    ]
