# Generated by Django 5.2.5 on 2026-01-15 13:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_notes_to_storeorder'),
        ('products', '0006_productrecipe_alter_expense_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returneditem',
            options={'ordering': ['-returned_at'], 'verbose_name': 'Возвращённый товар', 'verbose_name_plural': 'Возвращённые товары'},
        ),
        migrations.AddField(
            model_name='returneditem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Только для весовых товаров, шаг 0.1 кг', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='orders.storeorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='price_at_return',
            field=models.DecimalField(decimal_places=2, help_text='За 1 шт или за 1 кг для весовых', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена на момент возврата'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Для штучных: количество шт, для весовых: обычно 1', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина возврата'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='returned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_items', to=settings.AUTH_USER_MODEL, verbose_name='Кто вернул'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма'),
        ),
        migrations.AddIndex(
            model_name='returneditem',
            index=models.Index(fields=['-returned_at'], name='returned_it_returne_65ea55_idx'),
        ),
    ]
