# Generated by Django 5.2.5 on 2026-01-29 04:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_returneditem_options_returneditem_weight_and_more'),
        ('products', '0006_productrecipe_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос партнёра', 'verbose_name_plural': 'Запросы партнёров'},
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные примечания к запросу', verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Только для весовых товаров, шаг 0.1 кг', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Для обратной совместимости. Используйте items для v3.0', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_requests', to='products.product'),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Для обратной совместимости. Используйте items для v3.0', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.CreateModel(
            name='PartnerRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Для штучных: количество шт. Для весовых: обычно 1', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Только для весовых товаров, шаг 0.1 кг', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Вес (кг)')),
                ('price_at_request', models.DecimalField(decimal_places=2, help_text='За 1 шт или за 1 кг для весовых', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена на момент запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_request_items', to='products.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.partnerrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Позиция запроса партнёра',
                'verbose_name_plural': 'Позиции запросов партнёров',
                'db_table': 'partner_request_items',
                'indexes': [models.Index(fields=['request', 'product'], name='partner_req_request_57e212_idx')],
                'unique_together': {('request', 'product')},
            },
        ),
    ]
