# Generated by Django 5.2.5 on 2026-01-29 04:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_weight_fields_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectiveproduct',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Только для весовых товаров', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Вес (кг)'),
        ),
    ]
