# Generated by Django 5.2.5 on 2026-02-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_weight_to_defective'),
        ('products', '0007_add_preview_to_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectiveproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Для обратной совместимости. Используйте items для v3.0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to='products.product'),
        ),
        migrations.AlterField(
            model_name='partnerrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_request_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_order_items', to='products.product', verbose_name='Товар'),
        ),
    ]
