# Generated by Django 5.2.5 on 2026-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_product_cascade_delete'),
        ('products', '0007_add_preview_to_productimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerrequestitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partnerrequestitem',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='Запрос на получение бонусного товара', verbose_name='Бонусный запрос'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerrequestitem',
            unique_together={('request', 'product', 'is_bonus')},
        ),
        migrations.AddIndex(
            model_name='partnerrequestitem',
            index=models.Index(fields=['is_bonus'], name='partner_req_is_bonu_928a2f_idx'),
        ),
    ]
