# Generated by Django 6.0.2 on 2026-03-03 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_partnerrequestitem_unique_together_and_more'),
        ('stores', '0012_alter_store_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'status'], name='store_order_store_i_dbab53_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['partner', 'status'], name='store_order_partner_08da15_idx'),
        ),
    ]
