# Generated by Django 6.0.2 on 2026-04-03 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_store_partner_status_indexes'),
        ('stores', '0012_alter_store_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Магазин, по которому погашается долг', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Может быть null при оплате админом без привязки к заказу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='orders.storeorder', verbose_name='Заказ'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['store', '-created_at'], name='debt_paymen_store_i_67183b_idx'),
        ),
    ]
