# Generated by Django 6.0.2 on 2026-04-03 09:29

from django.db import migrations


def backfill_store(apps, schema_editor):
    """Заполняем store из order.store для существующих DebtPayment."""
    DebtPayment = apps.get_model('orders', 'DebtPayment')
    for dp in DebtPayment.objects.filter(store__isnull=True, order__isnull=False).select_related('order'):
        dp.store_id = dp.order.store_id
        dp.save(update_fields=['store_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_debt_payment_optional_order_add_store'),
    ]

    operations = [
        migrations.RunPython(backfill_store, migrations.RunPython.noop),
    ]
