# Generated by Django 5.2.5 on 2025-11-28 08:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('reason', models.TextField(verbose_name='Причина брака')),
                ('status', models.CharField(choices=[('reported', 'Сообщено'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='reported', max_length=20, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
            ],
            options={
                'verbose_name': 'Бракованный товар',
                'verbose_name_plural': 'Бракованные товары',
                'db_table': 'defective_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('expense_type', models.CharField(choices=[('physical', 'Физические (ингредиенты)'), ('overhead', 'Накладные (постоянные)')], max_length=20, verbose_name='Тип расхода')),
                ('accounting_mode', models.CharField(choices=[('dynamic', 'Динамичный (зависит от производства)'), ('static', 'Статичный (фиксированная сумма)')], default='dynamic', help_text='Динамичный — для ингредиентов, Статичный — для аренды/зарплаты', max_length=20, verbose_name='Режим учёта')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Цена за 1 кг/шт/литр ингредиента', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('unit', models.CharField(blank=True, choices=[('piece', 'Штука'), ('kg', 'Килограмм'), ('gram', 'Грамм'), ('liter', 'Литр')], max_length=10, null=True, verbose_name='Единица измерения')),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Фиксированная сумма для накладных расходов', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма в месяц')),
                ('status', models.CharField(choices=[('suzerain', 'Сюзерен (главный)'), ('vassal', 'Вассал (зависимый)'), ('civilian', 'Обыватель (базовый)')], default='civilian', max_length=20, verbose_name='Статус')),
                ('state', models.CharField(choices=[('mechanical', 'Механическое (ручной ввод)'), ('automatic', 'Автоматическое (расчёт)')], default='automatic', max_length=20, verbose_name='Состояние учёта')),
                ('apply_type', models.CharField(choices=[('regular', 'Обычный (выборочно)'), ('universal', 'Универсальный (ко всем)')], default='regular', max_length=20, verbose_name='Тип применения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'db_table': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MechanicalExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Потрачено')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запись механического учёта',
                'verbose_name_plural': 'Записи механического учёта',
                'db_table': 'mechanical_expense_entries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_weight_based', models.BooleanField(default=False, help_text='Продаётся на вес с шагом 0.1 кг (минимум 1 кг, если остаток >= 1 кг)', verbose_name='Весовой товар')),
                ('unit', models.CharField(choices=[('piece', 'Штука'), ('kg', 'Килограмм'), ('liter', 'Литр'), ('pack', 'Упаковка')], default='piece', max_length=10, verbose_name='Единица измерения')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена, установленная администратором', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Базовая цена')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Рассчитывается автоматически из расходов', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Себестоимость')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Процент наценки к себестоимости', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Наценка (%)')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена с наценкой для партнёров и магазинов', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Итоговая цена')),
                ('price_per_100g', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Автоматически рассчитывается для весовых товаров', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за 100г')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное изображение')),
                ('popularity_weight', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Чем выше — тем больше накладных расходов несёт товар', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Коэффициент популярности')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Устаревшее поле, использовать final_price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена (deprecated)')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость')),
                ('markup_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Наценка (сумма)')),
                ('ingredient_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Расход на ингредиенты')),
                ('overhead_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Накладные расходы')),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Общий расход')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Доход')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Прибыль')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, verbose_name='Последний расчёт')),
                ('is_outdated', models.BooleanField(default=True, verbose_name='Требует пересчёта')),
            ],
            options={
                'verbose_name': 'Кеш себестоимости',
                'verbose_name_plural': 'Кеши себестоимости',
                'db_table': 'product_cost_snapshots',
            },
        ),
        migrations.CreateModel(
            name='ProductExpenseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('proportion', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12, verbose_name='Пропорция')),
            ],
            options={
                'verbose_name': 'Связь товара с расходом (legacy)',
                'verbose_name_plural': 'Связи товаров с расходами (legacy)',
                'db_table': 'product_expense_relations',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'product_images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('quantity_produced', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество произведённого')),
                ('suzerain_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Если указано, количество товара рассчитывается автоматически', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество Сюзерена')),
                ('ingredient_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Стоимость ингредиентов')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Накладные расходы')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Общая себестоимость')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Себестоимость единицы')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Выручка')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Чистая прибыль')),
            ],
            options={
                'verbose_name': 'Позиция производства',
                'verbose_name_plural': 'Позиции производства',
                'db_table': 'production_items',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateField(verbose_name='Дата производства')),
            ],
            options={
                'verbose_name': 'Запись производства',
                'verbose_name_plural': 'Записи производства',
                'db_table': 'production_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ingredient_amount', models.DecimalField(decimal_places=3, help_text='Сколько ингредиента уходит (например, 50 кг муки)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество ингредиента')),
                ('output_quantity', models.DecimalField(decimal_places=3, help_text='На какое количество товара (например, 5000 булочек)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество продукции')),
                ('proportion', models.DecimalField(decimal_places=6, default=Decimal('0'), editable=False, help_text='Автоматически: ingredient_amount / output_quantity', max_digits=12, verbose_name='Пропорция на единицу')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'product_recipes',
            },
        ),
        migrations.CreateModel(
            name='StoreProductCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Всего куплено')),
                ('bonuses_given', models.PositiveIntegerField(default=0, verbose_name='Выдано бонусов')),
                ('last_bonus_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний бонус')),
            ],
            options={
                'verbose_name': 'Счётчик товаров',
                'verbose_name_plural': 'Счётчики товаров',
                'db_table': 'store_product_counters',
            },
        ),
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество бонусных единиц')),
                ('bonus_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Стоимость бонуса')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='orders.storeorder', verbose_name='Заказ')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'История бонусов',
                'verbose_name_plural': 'История бонусов',
                'db_table': 'bonus_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
