# Generated by Django 5.2.5 on 2025-12-05 04:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('expense_type', models.CharField(choices=[('physical', 'Физические'), ('overhead', 'Накладные')], max_length=10, verbose_name='Тип')),
                ('expense_status', models.CharField(choices=[('suzerain', 'Сюзерен'), ('vassal', 'Вассал'), ('civilian', 'Обыватель')], default='civilian', max_length=10)),
                ('expense_state', models.CharField(choices=[('mechanical', 'Механическое'), ('automatic', 'Автоматическое')], default='automatic', max_length=15)),
                ('apply_type', models.CharField(choices=[('regular', 'Обычный'), ('universal', 'Универсальный')], default='regular', max_length=10)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Например: Аренда 35,000 сом/месяц', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Месячная сумма')),
                ('daily_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Например: Фарш 28,350 сом/день', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Дневная сумма')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'db_table': 'expenses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='expenses_is_acti_4933c3_idx'), models.Index(fields=['expense_type'], name='expenses_expense_272666_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Описание')),
                ('is_weight_based', models.BooleanField(default=False, verbose_name='Весовой товар')),
                ('unit', models.CharField(choices=[('piece', 'Штука'), ('kg', 'Килограмм'), ('liter', 'Литр'), ('pack', 'Упаковка')], default='piece', max_length=10, verbose_name='Единица измерения')),
                ('average_cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Обновляется из производства', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Себестоимость')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Устанавливается админом', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))], verbose_name='Наценка (%)')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='АВТОМАТИЧЕСКИ рассчитывается', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена продажи')),
                ('price_per_100g', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена за 100г')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='На складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Бонусный')),
                ('popularity_weight', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Коэффициент популярности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'is_available'], name='products_is_acti_706d22_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductExpenseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='products.expense')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_relations', to='products.product')),
            ],
            options={
                'db_table': 'product_expense_relations',
                'unique_together': {('product', 'expense')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'product_images',
                'ordering': ['product', 'order'],
                'unique_together': {('product', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата производства')),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Произведено')),
                ('total_daily_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Дневные расходы')),
                ('total_monthly_expenses_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Месячные (на день)')),
                ('cost_price_calculated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Производственная партия',
                'verbose_name_plural': 'Производственные партии',
                'db_table': 'production_batches',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product', '-date'], name='production__product_8d0770_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
