# Generated by Django 5.2.5 on 2025-11-28 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonushistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='defective_products', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'is_active'], name='expenses_expense_58ea5d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['accounting_mode', 'is_active'], name='expenses_account_1e270b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expenses_status_86293f_idx'),
        ),
        migrations.AddField(
            model_name='mechanicalexpenseentry',
            name='expense',
            field=models.ForeignKey(limit_choices_to={'state': 'mechanical'}, on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_entries', to='products.expense', verbose_name='Расход'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_available'], name='products_is_acti_706d22_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_weight_based'], name='products_is_weig_4ccce8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productcostsnapshot',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshot', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productexpenserelation',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='products.expense', verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='productexpenserelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_relations', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='productionitem',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productionrecord', verbose_name='Запись производства'),
        ),
        migrations.AddField(
            model_name='mechanicalexpenseentry',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_entries', to='products.productionrecord', verbose_name='Запись производства'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='expense',
            field=models.ForeignKey(limit_choices_to={'expense_type': 'physical'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.expense', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_counters', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_counters', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_counters', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddIndex(
            model_name='defectiveproduct',
            index=models.Index(fields=['status'], name='defective_p_status_6017ea_idx'),
        ),
        migrations.AddIndex(
            model_name='defectiveproduct',
            index=models.Index(fields=['partner', 'status'], name='defective_p_partner_f8b3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='productcostsnapshot',
            index=models.Index(fields=['is_outdated'], name='product_cos_is_outd_3ffda5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productexpenserelation',
            unique_together={('product', 'expense')},
        ),
        migrations.AddIndex(
            model_name='productionrecord',
            index=models.Index(fields=['partner', 'date'], name='production__partner_33b9a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionrecord',
            unique_together={('partner', 'date')},
        ),
        migrations.AddIndex(
            model_name='productionitem',
            index=models.Index(fields=['record', 'product'], name='production__record__522e5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionitem',
            unique_together={('record', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='mechanicalexpenseentry',
            unique_together={('record', 'expense')},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['product'], name='product_rec_product_b4d68d_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['expense'], name='product_rec_expense_e9952a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('product', 'expense')},
        ),
        migrations.AddIndex(
            model_name='storeproductcounter',
            index=models.Index(fields=['store', 'partner'], name='store_produ_store_i_f31633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproductcounter',
            unique_together={('store', 'partner', 'product')},
        ),
    ]
