# Generated by Django 5.2.5 on 2025-12-05 19:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма расхода в сомах', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма расхода')),
                ('description', models.TextField(help_text='Причина/описание расхода', verbose_name='Описание расхода')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Расход партнёра',
                'verbose_name_plural': 'Расходы партнёров',
                'db_table': 'partner_expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['name'], 'verbose_name': 'Расход (производство)', 'verbose_name_plural': 'Расходы (производство)'},
        ),
        migrations.AlterModelOptions(
            name='productexpenserelation',
            options={'verbose_name': 'Связь товар-расход', 'verbose_name_plural': 'Связи товар-расход'},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddField(
            model_name='partnerexpense',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddIndex(
            model_name='partnerexpense',
            index=models.Index(fields=['partner', '-date'], name='partner_exp_partner_ba349e_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerexpense',
            index=models.Index(fields=['date'], name='partner_exp_date_ac11f9_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerexpense',
            index=models.Index(fields=['-created_at'], name='partner_exp_created_63a7e6_idx'),
        ),
    ]
