# Generated by Django 5.2.5 on 2025-12-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_partnerexpense_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Максимум 250 символов', verbose_name='Описание'),
        ),
    ]
