# Generated by Django 5.2.5 on 2025-12-13 11:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dependency_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Только для Вассалов: какая пропорция от Сюзерена (например: 0.095)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Коэффициент зависимости'),
        ),
        migrations.AddField(
            model_name='expense',
            name='depends_on_suzerain',
            field=models.ForeignKey(blank=True, help_text='Только для Вассалов: от какого Сюзерена зависит количество', limit_choices_to={'expense_status': 'suzerain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vassals', to='products.expense', verbose_name='Зависит от Сюзерена'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Для Сюзеренов - вводится вручную, для Вассалов - рассчитывается автоматически', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Для расчёта суммы расхода', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
    ]
