# Generated by Django 5.2.5 on 2025-12-29 14:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_expense_dependency_ratio_expense_depends_on_suzerain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='unit_type',
            field=models.CharField(choices=[('per_piece', 'По штукам'), ('per_weight', 'По весу (кг)')], default='per_piece', help_text='По штукам или по весу (кг)', max_length=15, verbose_name='Тип учёта'),
        ),
        migrations.AddField(
            model_name='product',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если установлена, используется вместо автоматического расчёта', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ручная цена'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='apply_type',
            field=models.CharField(choices=[('regular', 'Обычный'), ('universal', 'Универсальный')], default='regular', help_text='Универсальный = применяется ко всем товарам (свет, аренда)', max_length=10, verbose_name='Тип применения'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_state',
            field=models.CharField(choices=[('mechanical', 'Механическое'), ('automatic', 'Автоматическое')], default='automatic', max_length=15, verbose_name='Состояние учёта'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_status',
            field=models.CharField(choices=[('suzerain', 'Сюзерен'), ('vassal', 'Вассал'), ('civilian', 'Обыватель')], default='civilian', max_length=10, verbose_name='Статус в иерархии'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Для Сюзеренов - вводится вручную, для Вассалов - рассчитывается', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена за штуку или за кг (в зависимости от unit_type)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Авторасчёт или manual_price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bonus',
            field=models.BooleanField(default=False, help_text='Каждый 21-й товар бесплатно (только для штучных)', verbose_name='Бонусный'),
        ),
        migrations.AlterField(
            model_name='productexpenserelation',
            name='proportion',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Пропорция расхода для товара (опционально)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_status'], name='expenses_expense_f8f184_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bonus'], name='products_is_bonu_63fc46_idx'),
        ),
    ]
