# Generated by Django 5.2.5 on 2026-01-02 10:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_expense_unit_type_product_manual_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(blank=True, decimal_places=4, help_text='Для Сюзерена: кг/шт на 1 единицу товара', max_digits=12, null=True, verbose_name='Количество на единицу')),
                ('proportion', models.DecimalField(blank=True, decimal_places=3, help_text='Пропорция от Сюзерена (например, 0.5 = 50%)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Пропорция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рецепт товара',
                'verbose_name_plural': 'Рецепты товаров',
                'db_table': 'product_recipes',
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['name'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='partnerexpense',
            options={'ordering': ['-date'], 'verbose_name': 'Расход партнёра', 'verbose_name_plural': 'Расходы партнёров'},
        ),
        migrations.AlterModelOptions(
            name='productexpenserelation',
            options={'verbose_name': 'Связь товар-расход (устарело)', 'verbose_name_plural': 'Связи товар-расход (устарело)'},
        ),
        migrations.AlterModelOptions(
            name='productionbatch',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Производственная партия', 'verbose_name_plural': 'Производственные партии'},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_is_acti_4933c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_expense_272666_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerexpense',
            name='partner_exp_date_ac11f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerexpense',
            name='partner_exp_created_63a7e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_name_6f9890_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_bonu_63fc46_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productionbatch',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='partnerexpense',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_100g',
        ),
        migrations.AddField(
            model_name='expense',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для физических: цена за 1 кг/шт', max_digits=10, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость за единицу'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='input_type',
            field=models.CharField(choices=[('quantity', 'От количества товара'), ('suzerain', 'От объёма Сюзерена')], default='quantity', max_length=20, verbose_name='Тип ввода'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='total_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Накладные расходы'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='total_physical_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Физические расходы'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='apply_type',
            field=models.CharField(choices=[('regular', 'Обычный'), ('universal', 'Универсальный')], default='regular', help_text='Обычный (к отдельным товарам) или Универсальный (ко всем)', max_length=10, verbose_name='Тип применения'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='daily_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Дневная сумма'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='dependency_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пропорция от Сюзерена (например, 0.5 = 50%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Коэффициент зависимости'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='depends_on_suzerain',
            field=models.ForeignKey(blank=True, limit_choices_to={'expense_status': 'suzerain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vassals', to='products.expense', verbose_name='Зависит от Сюзерена'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_state',
            field=models.CharField(choices=[('mechanical', 'Механическое'), ('automatic', 'Автоматическое')], default='automatic', help_text='Механическое (ручной ввод) или Автоматическое (расчётное)', max_length=15, verbose_name='Состояние учёта'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_status',
            field=models.CharField(choices=[('suzerain', 'Сюзерен'), ('vassal', 'Вассал'), ('civilian', 'Обыватель')], default='civilian', help_text='Сюзерен (главный), Вассал (зависимый), Обыватель (базовый)', max_length=10, verbose_name='Статус в иерархии'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('physical', 'Физические'), ('overhead', 'Накладные')], help_text='Физические (ингредиенты) или Накладные (операционные)', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Месячная сумма'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(help_text='Например: Мука, Фарш, Аренда, Зарплата', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('per_piece', 'По штукам'), ('per_weight', 'По весу (кг)')], help_text='По штукам или По весу (только для физических)', max_length=15, null=True, verbose_name='Тип учёта'),
        ),
        migrations.AlterField(
            model_name='partnerexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='partnerexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partnerexpense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='partnerexpense',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='partnerexpense',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Средняя себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bonus',
            field=models.BooleanField(default=False, verbose_name='Бонусный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ручная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Наценка (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Для умной наценки (перераспределение накладных)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Коэффициент популярности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Килограмм'), ('piece', 'Штука'), ('liter', 'Литр')], default='piece', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productexpenserelation',
            name='proportion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'is_active'], name='expenses_expense_58ea5d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['-date'], name='production__date_718afe_idx'),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='products.expense', verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='cost_price_calculated',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='total_daily_expenses',
        ),
        migrations.RemoveField(
            model_name='productionbatch',
            name='total_monthly_expenses_per_day',
        ),
        migrations.AddIndex(
            model_name='productrecipe',
            index=models.Index(fields=['product', 'expense'], name='product_rec_product_39aa97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecipe',
            unique_together={('product', 'expense')},
        ),
    ]
