# Generated by Django 5.2.5 on 2026-02-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productrecipe_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='products/previews/%Y/%m/', verbose_name='Превью'),
        ),
    ]
