# Generated by Django 5.2.5 on 2026-02-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_preview_to_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='default_quantity_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Для универсальных физических: кол-во на 1 единицу товара', max_digits=12, null=True, verbose_name='Норма на единицу по умолчанию'),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='absolute_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Что вводит пользователь (например 40 кг лука)', max_digits=12, null=True, verbose_name='Абсолютное количество'),
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='product_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для Сюзерена: на сколько единиц рассчитано (например 40 пачек)', max_digits=12, null=True, verbose_name='Количество единиц товара'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('per_piece', 'По штукам'), ('per_weight', 'По весу (кг)'), ('per_volume', 'По объёму (литр)')], help_text='По штукам или По весу (только для физических)', max_length=15, null=True, verbose_name='Тип учёта'),
        ),
    ]
