# Generated by Django 6.0.2 on 2026-02-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_expense_default_quantity_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(help_text='Например: Мука, Фарш, Аренда, Зарплата', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
