# Generated by Django 6.0.2 on 2026-03-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_fix_suzerain_quantity_per_unit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_state'], name='expenses_expense_eddfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'expense_state', 'is_active'], name='expenses_expense_30ad0d_idx'),
        ),
    ]
