# Generated by Django 6.0.2 on 2026-04-03 08:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_expense_expenses_expense_eddfa1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Цена для Ош, Цена для Бишкек', max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_prices', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительная цена',
                'verbose_name_plural': 'Дополнительные цены',
                'db_table': 'additional_prices',
                'ordering': ['product', 'price'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='additional__product_097cee_idx')],
            },
        ),
    ]
